linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - revive
    - rowserrcheck
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

disable:
#  - name_of_linter

issues:
  exclude-rules:
    - path: main.go
      linters:
        - gocritic
        - gosec